### PR TITLE
CON-1240: Fix EnclaveInfo integration test under Gramine

### PR DESCRIPTION
**Pull request by shamsasari**
This test has been updated to work under both GraalVM and Gramine. We used to have native code that read the sections of the .so file to extract out the enclave metadata. This is no longer needed and has been removed. Instead the sgx_sign tool is used to extract out the `SIGSTRUCT` data structure. Gramine writes this structure out in the .sig file. This isn't generated by gramine-direct in simulation mode, so the manifest file is checked instead.

`SgxMetadataEnclaveCss`, which represents the `SIGSTRUCT`, has been renamed to `SgxEnclaveCss` to better reflect the naming in the SGX SDK code.

The generateEnclaveMetadata task has also been improved to use the `SIGSTRUCT` dump from sgx_sign, rather than the fiddly text output.

### CODE REVIEW

**Comment by shamsasari** [comment]
Currently not able to test this on my SGX VM due to the following error:
```
AttestationTests > EnclaveInfo matches SIGSTRUCT() FAILED
    com.r3.conclave.host.EnclaveLoadException: Unable to start enclave
        at app//com.r3.conclave.host.EnclaveHost.start(EnclaveHost.kt:459)
        at app//com.r3.conclave.host.internal.EnclaveHostService.start(EnclaveHostService.kt:39)
        at app//com.r3.conclave.integrationtests.general.commontest.TestEnclaveTransport.startEnclave(TestEnclaveTransport.kt:33)
        at app//com.r3.conclave.integrationtests.general.commontest.AbstractEnclaveActionTest$getEnclaveTransport$1$1.invoke(AbstractEnclaveActionTest.kt:90)
        at app//com.r3.conclave.integrationtests.general.commontest.AbstractEnclaveActionTest$getEnclaveTransport$1$1.invoke(AbstractEnclaveActionTest.kt:84)
        at app//com.r3.conclave.integrationtests.general.commontest.AbstractEnclaveActionTest.getEnclaveTransport$lambda$4$lambda$3(AbstractEnclaveActionTest.kt:84)
        at java.base@17.0.5/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at app//com.r3.conclave.integrationtests.general.commontest.AbstractEnclaveActionTest.getEnclaveTransport(AbstractEnclaveActionTest.kt:84)
        at app//com.r3.conclave.integrationtests.general.commontest.AbstractEnclaveActionTest.enclaveHost(AbstractEnclaveActionTest.kt:53)
        at app//com.r3.conclave.integrationtests.general.commontest.AbstractEnclaveActionTest.enclaveHost$default(AbstractEnclaveActionTest.kt:52)
        at app//com.r3.conclave.integrationtests.general.tests.AttestationTests.EnclaveInfo matches SIGSTRUCT(AttestationTests.kt:54)

        Caused by:
        java.lang.IllegalStateException: Not a PCK cert path: 3
            at com.r3.conclave.common.internal.SgxTypesKt.toPckCertPath(SgxTypes.kt:622)
            at com.r3.conclave.host.internal.attestation.DCAPAttestationService.doAttestQuote(DCAPAttestationService.kt:19)
            at com.r3.conclave.host.internal.attestation.DCAPAttestationService.doAttestQuote(DCAPAttestationService.kt:17)
            at com.r3.conclave.host.internal.attestation.HardwareAttestationService.attestQuote(AttestationService.kt:27)
            at com.r3.conclave.host.internal.attestation.HardwareAttestationService.attestQuote(AttestationService.kt:23)
            at com.r3.conclave.host.EnclaveHost.getAttestation(EnclaveHost.kt:547)
            at com.r3.conclave.host.EnclaveHost.updateAttestation(EnclaveHost.kt:538)
            at com.r3.conclave.host.EnclaveHost.start(EnclaveHost.kt:431)
            ... 10 more
```

The hello world sample on the same VM has the same error, which is known to have worked. It seems, at least on my VM, we're using a different method to verify the PCK.

**Comment by shamsasari** [comment]
I need to re-run the integration tests manually on VM with the updated instructions for Gramine RA.

**Review by ac101m — COMMENTED** [review]
looks good to me, will leave it to marco to approve

**Comment by shamsasari** [comment]
I can confirm that the test passes for Gramine debug.

**Comment by bonifazi-r3** [comment]
Which test are we talking about?

**Comment by bonifazi-r3** [comment]
No idea how I closed this one @shamsasari , was just adding a m

**Comment by bonifazi-r3** [comment]
Also, is there a Jira?

**Comment by shamsasari** [comment]
The EnclaveInfo test in AttestationTests

**Review by bonifazi-r3 — APPROVED** [review]

**Comment by bonifazi-r3** [comment]
There are building issues, I believe due to renaming of functions or cherry pick from other repo? `AttestationTests` seem to have wrong imports

**Pull request merged**
